# Generated by Django 5.1.6 on 2026-01-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salon')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='scheduling.professional')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.professional')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salon')),
            ],
        ),
    ]
