# Generated by Django 5.1.6 on 2026-01-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0002_holiday_professionalbreak_specialschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='core.salon'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='scheduling.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='scheduling.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.salon'),
        ),
    ]
