# Generated by Django 5.1.6 on 2026-01-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_professional_foto_alter_professional_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='codigo_validacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
