# Generated by Django 5.1.6 on 2026-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_appointment_codigo_validacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
