# Generated by Django 5.1.6 on 2026-01-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_holiday_hora_fim_holiday_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='intervalos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
