# Generated by Django 5.1.6 on 2026-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='horarios_customizados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
